import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fcf9f4",
        "surface-dim": "#dcdad5",
        "surface-bright": "#fcf9f4",
        "surface-variant": "#e5e2dd",
        "surface-tint": "#476083",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3ee",
        "surface-container": "#f0ede8",
        "surface-container-high": "#ebe8e3",
        "surface-container-highest": "#e5e2dd",
        "background": "#fcf9f4",
        "on-background": "#1c1c19",
        "on-surface": "#1c1c19",
        "on-surface-variant": "#3d4850",
        "primary": "#476083",
        "primary-container": "#9bb3db",
        "primary-fixed": "#d4e3ff",
        "primary-fixed-dim": "#afc8f0",
        "on-primary": "#ffffff",
        "on-primary-container": "#2c4567",
        "on-primary-fixed": "#001c3a",
        "on-primary-fixed-variant": "#2f486a",
        "inverse-primary": "#afc8f0",
        "secondary": "#00668a",
        "secondary-container": "#00bdfd",
        "secondary-fixed": "#c3e8ff",
        "secondary-fixed-dim": "#7ad0ff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#004964",
        "on-secondary-fixed": "#001e2c",
        "on-secondary-fixed-variant": "#004c69",
        "tertiary": "#a43c12",
        "tertiary-container": "#ff9772",
        "tertiary-fixed": "#ffdbcf",
        "tertiary-fixed-dim": "#ffb59c",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#7e2600",
        "on-tertiary-fixed": "#380c00",
        "on-tertiary-fixed-variant": "#822800",
        "outline": "#6d7981",
        "outline-variant": "#bcc8d1",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#31302d",
        "inverse-on-surface": "#f3f0eb",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "sans-serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-plus-jakarta-sans)", "sans-serif"],
        sacrifice: ["var(--font-sacrifice)", "cursive"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
export default config;
